environment:
  GITHUB_TOKEN: ENCRYPTED[706dbe0caf40102254d645bf9b4351d2e822b0aa567dce1b47d066c2b5b573c804c754a2a689ea8ee926f6610e42e393]

task:
  name: Microwave
  timeout_in: 120m
  container:
    image: vcyzteen/bakaburn:latest
    platform: linux
    cpu: 16.0
    memory: 32G
  setup_git_script:
    - git config --global user.email "vcyzscape@gmail.com"
    - git config --global user.name "vcyzteen"
  start_heating_script:
    - bash microwave
