--- 
clone: 
  depth: 1
kind: pipeline
name: microwave
steps: 
  - 
    commands: 
      - "bash ./run.sh"
    environment: 
      TELEGRAM_TOKEN: 
        from_secret: BOT_API_KEY
      GITHUB_TOKEN:
        from_secret: GH_TOKEN
    image: vcyzteen/bakaburn:latest
    name: microwave
    trigger: 
      branch: 
        - unified-tes
