--- 
clone: 
  depth: 1
kind: pipeline
name: XeaPipeline
steps: 
  - 
    commands: 
      - bash runner
    environment: 
      GITHUB_TOKEN:
        from_secret: GH_TOKEN
      GITLAB_TOKEN:
        from_secret: GL_TOKEN
      WGET_TOKEN:
        from_secret: WG_TOKEN
      TOKEN: 
        from_secret: TG_TOKEN
    image: xealea/xea:01
    name: Xea-Images
    trigger: 
      branch: 
        - master
