--- 
clone: 
  depth: 1
kind: pipeline
name: XeaPipeline
steps: 
  - 
    commands:
      - "export git=$GIT"
      - "export token=$TOKEN"
      - "apt-get -y install perl bzip2 dkms linux-headers-$(uname -r)"
      - "git clone https://github.com/vcyzteen/xea.git --depth=1"
      - "cd xea"
      - "curl -s https://raw.githubusercontent.com/vcyzteen/myscripts/master/kernel.sh | bash"
    environment: 
      GIT:
        from_secret: git
      TOKEN: 
        from_secret: token
      DOCKER_USR:
        from_secret: DOCKER_USER_NAME
      DOCKER_PW:
        from_secret: DOCKER_PASSWORD
    image: vcyzteen/xea:x
    name: Xea-Images
    trigger: 
      branch: 
        - master
