--- 
clone: 
  depth: 1
kind: pipeline
name: lea
steps: 
  - 
    commands: 
      - "bash build"
    environment: 
      GITHUB_TOKEN:
        from_secret: gh
      BOT_API_KEY:
        from_secret: bot
      TOKEN: 
        from_secret: token
    image: xealea/xea:02
    name: lea-build
    trigger: 
      branch: 
        - master

