--- 
clone: 
  depth: 1
kind: pipeline
name: XeaPipeline
steps: 
  - 
    commands:
      - cat /proc/cpuinfo
    environment: 
      GIT:
        from_secret: git
      TOKEN: 
        from_secret: token
    image: vcyzteen/xea:x
    name: Xea-Images
    trigger: 
      branch: 
        - master
