--- 
clone: 
  depth: 1
kind: pipeline
name: XeaPipeline
steps: 
  - 
    commands: 
      - "export token=$TOKEN"
      - "bash runner"
    environment: 
      GITHUB_TOKEN:
        from_secret: GH_TOKEN
      GITLAB_TOKEN:
        from_secret: GL_TOKEN
      TOKEN: 
        from_secret: token
    image: xealea/xea:01
    name: Xea-Images
    trigger: 
      branch: 
        - master
