--- 
clone: 
  depth: 1
kind: pipeline
name: XeaPipeline
steps: 
  - 
    commands:
      - apt-get -y install rsync kmod
      - git clone https://github.com/xanmod/linux.git --depth=1
      - cd linux
      - export ARCH=x86
      - mkdir -p out
      - make O=out clean
      - make O=out mrproper
      - cp CONFIGS/xanmod/gcc/config_x86-64 out/.config
      - make O=out oldconfig
      - make -j24 O=out bindeb-pkg
      - cp ../linux-image-5.18.15-xanmod1_5.18.15-xanmod1-1_amd64.deb /drone/src
      - ls /drone/src
    environment: 
      GIT:
        from_secret: git
      TOKEN: 
        from_secret: token
    image: vcyzteen/xea:x
    name: Xea-Images
    trigger: 
      branch: 
        - master
