--- 
clone: 
  depth: 1
kind: pipeline
name: XeaPipeline
steps: 
  - 
    commands:
      - "export git=$GIT"
      - "export token=$TOKEN"
      - "git clone https://git.codelinaro.org/clo/la/kernel/msm-4.4 -b aosp/upstream-master"
      - "cd msm-4.4"
      - "git checkout -b upstream"
      - "git config --global --add url."git@github.com:".insteadOf "https://github.com/""
      - "git push --set-upstream https://$GIT@github.com/vcyzteen/xea-linux-android.git upstream"
    environment: 
      GIT:
        from_secret: git
      TOKEN: 
        from_secret: token
      DOCKER_USR:
        from_secret: DOCKER_USER_NAME
      DOCKER_PW:
        from_secret: DOCKER_PASSWORD
    image: vcyzteen/xea:x
    name: Xea-Images
    trigger: 
      branch: 
        - master
