--- 
clone: 
  depth: 1
kind: pipeline
name: XeaPipeline
steps: 
  - 
    commands:
      - "export git=$GIT"
      - "export token=$TOKEN"
      - "apt-get -y install clang llvm bolt"
      - "git clone https://github.com/xealea/x86-builder-gcc.git"
      - "cd x86-builder-gcc"
      - "chmod +x mostlyportable-gcc.sh"
      - "./mostlyportable-gcc.sh gcc"
    environment: 
      GIT:
        from_secret: git
      TOKEN: 
        from_secret: token
      DOCKER_USR:
        from_secret: DOCKER_USER_NAME
      DOCKER_PW:
        from_secret: DOCKER_PASSWORD
    image: xealea/xea:01
    name: Xea-Images
    trigger: 
      branch: 
        - master
