--- 
clone: 
  depth: 1
kind: pipeline
name: XeaPipeline
steps: 
  - 
    commands:
      - git clone https://$GIT@github.com/vcyzteen/burning-docker
      - docker build -f Dockerfile . -t vcyzteen/xea:gcc
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER_NAME" --password-stdin
      - docker push vcyzteen/xea:gcc
    environment: 
      GIT:
        from_secret: git
      TOKEN: 
        from_secret: token
      DOCKER_USR:
        from_secret: DOCKER_USER_NAME
      DOCKER_PW:
        from_secret: DOCKER_PASSWORD
    image: vcyzteen/xea:x
    name: Xea-Images
    trigger: 
      branch: 
        - master
