--- 
clone: 
  depth: 1
kind: pipeline
name: XeaPipeline
steps: 
  - 
    commands:
      - "export git=$GIT"
      - "export token=$TOKEN"
      - "git clone https://github.com/xealea/xea-linux-x86"
      - "cd xea-linux-x86"
      - "curl -s https://raw.githubusercontent.com/xealea/builder-kernel-x86/master/debpkg | bash"
    environment: 
      GIT:
        from_secret: git
      TOKEN: 
        from_secret: token
      DOCKER_USR:
        from_secret: DOCKER_USER_NAME
      DOCKER_PW:
        from_secret: DOCKER_PASSWORD
    image: xealea/xea:01
    name: Xea-Images
    trigger: 
      branch: 
        - master
