--- 
clone: 
  depth: 1
kind: pipeline
name: XeaPipeline
steps: 
  - 
    commands:
      - "export git=$GIT"
      - "git clone --depth=1 https://$GIT@github.com/vcyzteen/xea.git"
      - "cd xea"
      - "export token=$TOKEN"
      - "curl https://raw.githubusercontent.com/vcyzteen/myscripts/master/kernel.sh | bash"
    environment: 
      GIT:
        from_secret: git
      TOKEN: 
        from_secret: token
    image: panchajanya1999/archlinux:latest
    name: Xea-Images
    trigger: 
      branch: 
        - master
