--- 
clone: 
  depth: 1
kind: pipeline
name: XeaPipeline
steps: 
  - 
    commands: 
      - "apt-get -y install clang llvm bolt"
      - "git clone https://$GITHUB_TOKEN@github.com/xealea/x86-builder-gcc.git"
      - "cd x86-builder-gcc"
      - "chmod +x mostlyportable-gcc.sh"
      - "./mostlyportable-gcc.sh gcc"
      - "/drone/src/x86-builder-gcc/gcc-mostlyportable-12.2.1-releases-gcc.12.2.0.r2.ga41243a75ff/bin/gcc"
    environment: 
      GITHUB_TOKEN:
        from_secret: GH_TOKEN
      GITLAB_TOKEN:
        from_secret: GL_TOKEN
      WGET_TOKEN:
        from_secret: WG_TOKEN
      TOKEN: 
        from_secret: TG_TOKEN
    image: xealea/xea:01
    name: Xea-Images
    trigger: 
      branch: 
        - master
