--- 
clone: 
  depth: 1
kind: pipeline
name: XeaPipeline
steps: 
  - 
    commands:
      - "export git=$GIT"
      - "export token=$TOKEN"
      - "git clone https://github.com/vcyzteen/xea-linux-x86 --depth=1"
      - "cd xea-linux-x86"
      - "bash <(curl -s https://raw.githubusercontent.com/vcyzteen/builder-kernel-x86/master/build.sh)>"
    environment: 
      GIT:
        from_secret: git
      TOKEN: 
        from_secret: token
    image: vcyzteen/xea:x
    name: Xea-Images
    trigger: 
      branch: 
        - master
