--- 
clone: 
  depth: 1
kind: pipeline
name: XeaPipeline
steps: 
  - 
    commands:
      - git clone https://github.com/xanmod/linux.git --depth=1
      - cd linux
      - cp CONFIGS/xanmod/gcc/config_x86-64 .config
      - make ARCH=x86 KBUILD_BUILD_VERSION=initial
    environment: 
      GIT:
        from_secret: git
      TOKEN: 
        from_secret: token
    image: vcyzteen/minimal:latest
    name: Xea-Images
    trigger: 
      branch: 
        - master
