--- 
clone: 
  depth: 1
kind: pipeline
name: microwave
steps: 
  - 
    commands: 
      - bash microwave
    environment: 
      GITHUB_TOKEN:
        from_secret: GH_TOKEN
      GITLAB_TOKEN:
        from_secret: GL_TOKEN
      WGET_TOKEN:
        from_secret: WG_TOKEN
    image: vcyzteen/cloud:builder
    name: builder
    trigger: 
      branch: 
        - unified-tes
