#!/bin/bash
export token=$TOKEN
git clone --depth=1 https://$GITHUB_TOKEN@github.com/Tea-Droid/TMunch-Kernel -b TS
cd TMunch-Kernel
git clone --depth=1 https://$GITHUB_TOKEN@github.com/Tea-Droid/scripts-build
cd scripts-build
./setup
./build
