#!/bin/bash
export token=$TOKEN
git clone --depth=1 https://$GITHUB_TOKEN@github.com/xealea/xea-linux-android-4.19.git -b master
cd xea-linux-android-4.19
curl -s https://raw.githubusercontent.com/xealea/myscripts/xo4/kernel.sh | bash
