#!/bin/bash
export token=$TOKEN
apt-get install -y clang-13
git clone --depth=1 https://github.com/xealea/xea-linux-x86 -b 6.0
cd xea-linux-x86
curl -s https://raw.githubusercontent.com/xealea/builder-kernel-x86/clang/debpkg | bash
